### ISSUE TITLE
Calendar widget not showing up

### ISSUE THREAD

**Issue by tobast** [bartromgens/care#13]
It seems that the `"pickTime": False` option given to `DateTimePicker`s prevents them from showing up on my setup. Do you have the same behaviour? Simply removing this argument works for me, and the widget does not try to make me pick a time anyway.

Also, it might be a good idea to switch to https://github.com/tutorcruncher/django-bootstrap3-datetimepicker/, as it is packaged as `django-bootstrap3-datetimepicker-2` in pip and is compatible with Django 1.11, but it looks a bit more cumbersome to use as it does not embed `bootstrap-datetime`'s js and css codes.

**Comment by tobast** [comment]
Workaround in tobast/care@99516dfd5

**Comment by bartromgens** [comment]
I can confirm this also doesn't work for me. Good find. The django-bootstrap3-datetimepicker version is not fixed so it probably broke in a newer version. 

I will check if it is easy to switch to `django-bootstrap3-datetimepicker-2`. Thanks for the suggestion.

**Comment by bartromgens** [comment]
Fixed by using the suggested `django-bootstrap3-datetimepicker-2` and removing the 'pickTime' argument.

**Comment by bartromgens** [comment]
@tobast This also made the upgrade to Django 1.11 possible, so that's what I did in commit https://github.com/bartromgens/care/commit/127a5272953977e6059c47567d7b853e1a3ee149
