### ISSUE TITLE
Cannot create group with PostgreSQL

### ISSUE THREAD

**Issue by tobast** [bartromgens/care#15]
The commit cef1f9b85b prevents a user from using PostgreSQL. Indeed, a `groupaccount`'s `number` is required by the form to be 11 digits, which will not fit in most databases' `int` fields (which are signed 32 bytes integers, thus limited to `2^31 - 1`, approximately `2 * 10^9`.

Also, the commit refers to issue #3, which seems to have nothing to do with this 11-digit identifier: is there any other bugtracker somewhere?

**Comment by bartromgens** [comment]
Good find. Not sure what this number is supposed to do. Probably was meant to be a unique identifier. I will have a look and see where it is used. Can probably reduce the size, remove it completely, or change the type to a CharField and create a unique ID with Python's uuid.

**Comment by bartromgens** [comment]
> Also, the commit refers to issue #3, which seems to have nothing to do with this 11-digit identifier: is there any other bugtracker somewhere?

@tobast This project was moved from BitBucket to GitHub a long time ago. That issue number is the old BitBucket issue, but GitHub is now the only place.

**Comment by bartromgens** [comment]
I completely removed the number model field because it was not used anywhere :)
